name: Deploy to Staging

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run: 
        working-directory: ./

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy to Staging
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "build/"
          target: "beta.mitchlui.dev"
          strip_components: 1
          overwrite: true
          



