name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run: 
        working-directory: ./
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: Tests
        run: pnpm test
        
      - name: Build
        run: pnpm build --if-present

      - name: Deploy to NameCheap
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "build/"
          target: "public_html"
          strip_components: 1
          overwrite: true
          



